env:
  global:
    - CC_TEST_REPORTER_ID=$CODE_CLIMATE_TOKEN

notifications:
  email: false

branches:
  only:
    - master

language: go

go:
  - "1.11.x"

install:
  - go get -t -v ./...

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -race -coverprofile=c.out -covermode=atomic ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
